export const INIT = 'INIT';
export const ADD_NEW_INVOICE = 'ADD_NEW_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const REMOVE_INVOICE = 'REMOVE_INVOICE';
export const CLEAR_INVOICES = 'CLEAR_INVOICES';
